export const miscSlugs = [
  'css-shadow-gen',
  'css-gradient-gen',
  'font-preview',
  'color-palette-gen',
  'aspect-ratio-calc',
  'random-color-combo',
  'barcode-gen',
  'number-to-korean',
  'consonant-extractor',
  'manuscript-calc',
  'korean-age-calc',
  'real-estate-fee-calc',
  'severance-pay-calc',
  'unemployment-benefit-calc',
  'korean-address-converter',
  'memorial-49-calc',
  'pomodoro-timer',
  'stopwatch',
  'timezone-converter',
  'checklist-gen',
  'workday-countdown',
  'fullscreen-clock',
  'online-scoreboard',
  'latitude-longitude-finder',
  'unit-converter',
  'celsius-fahrenheit',
  'emoji-search',
  'special-chars',
] as const

export type MiscSlug = typeof miscSlugs[number]
